import type { Metadata } from "next";
import Link from "next/link";
import { ConstituentTable } from "@/components/ConstituentTable";
import { ContributionRankings } from "@/components/ContributionRankings";
import { IndexChart } from "@/components/IndexChart";
import { IndexSummary } from "@/components/IndexSummary";
import { SectorAnalysis } from "@/components/SectorAnalysis";
import { IndexStatistics } from "@/components/indices/IndexStatistics";
import { hunterPowerIndex } from "@/data/indices/hunter-power";
import { calculateIndexStatistics } from "@/lib/index-engine/statistics";
import { getMarketSnapshot, type MarketSnapshot } from "@/lib/marketData";

export const metadata: Metadata = { title: "Hunter Power Index", description: "Hunter 电力指数（HPI）详情、成分、表现、贡献与方法论。" }; export const revalidate = 86_400;
async function loadIndex(): Promise<{ data: MarketSnapshot | null; error: string }> { try { return { data: await getMarketSnapshot(), error: "" }; } catch (error) { return { data: null, error: error instanceof Error ? error.message : "Data unavailable" }; } }
export default async function HunterPowerPage() { const result = await loadIndex(); const definition = hunterPowerIndex; const jsonLd = { "@context": "https://schema.org", "@type": "Dataset", name: definition.name, alternateName: definition.ticker, description: "Personal research index tracking the US power infrastructure value chain.", creator: { "@type": "Person", name: "Bangtao Li" }, license: "https://opensource.org/license/mit" }; return <main className="index-page terminal-section"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><section className="shell index-masthead"><div><span className="eyebrow">TAOTALK FINANCE · ORIGINAL INDICES</span><h1>{definition.nameZh}<small>{definition.name}</small></h1><p>Powering the Next Generation of Infrastructure</p></div><dl>{[["Ticker", definition.ticker], ["Base Value", String(definition.baseValue)], ["Currency", definition.currency], ["Weighting", definition.weighting], ["Rebalance", definition.rebalance]].map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section><div className="shell index-content">{result.data ? <><div className="data-asof"><span>{result.data.sourceLabel}</span><time>数据日 {result.data.dataDate} · {result.data.updatedAt}</time></div>{result.data.warnings.length > 0 && <details className="data-notice"><summary>数据说明 · {result.data.warnings.length} 项</summary><ul>{result.data.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></details>}<IndexSummary data={result.data} /><IndexStatistics data={calculateIndexStatistics(result.data.indexSeries, result.data.comparisonSeries)} /><IndexChart data={result.data.comparisonSeries} /><ConstituentTable rows={result.data.constituents} /><div className="analysis-grid"><SectorAnalysis sectors={result.data.sectors} /><ContributionRankings rows={result.data.constituents} /></div></> : <><div className="index-unavailable"><span>MARKET DATA UNAVAILABLE</span><h2>指数行情暂不可用</h2><p>{result.error}</p><small>未配置数据源时不生成替代行情。可在服务端环境变量中启用真实供应商；本地开发可显式开启 mock 模式。</small></div><section className="panel static-constituents"><div className="panel-heading"><h2>当前成分股 <small>{definition.constituents.length} 只</small></h2></div><div className="ticker-grid">{definition.constituents.map((item) => <div key={item.ticker}><b>{item.ticker}</b><span>{item.chineseName}</span><small>{item.sector} · {(item.weight * 100).toFixed(1)}%</small></div>)}</div></section></>}<section className="methodology-cta"><div><span className="eyebrow">INDEX METHODOLOGY</span><h2>透明、可复核的编制规则</h2><p>指数基于复权价格在服务端计算；季度再平衡，成分等权。Hunter 系列指数为个人研究编制的非官方指数。</p></div><Link className="button button-primary" href="/methodology/hunter-power">查看完整方法论</Link></section><p className="index-disclaimer">Hunter 系列指数不属于可投资金融产品，也不代表任何实际投资组合。数据来源和更新时间在每个图表或数据区块中单独标注。</p></div></main>; }
