"use client";
import { useEffect, useRef, useState } from "react";
import type { HistoricalRange } from "@/lib/market-data/types";

interface Series { symbol: string; name: string; source: string; updatedAt: string; points: Array<{ date: string; value: number }> }
const ranges: HistoricalRange[] = ["1M", "3M", "6M", "YTD", "1Y", "3Y", "MAX"];

export function MarketComparison() {
  const [range, setRange] = useState<HistoricalRange>("1Y"); const [series, setSeries] = useState<Series[]>([]); const [state, setState] = useState<"loading" | "ready" | "empty" | "error">("loading"); const chartRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/markets/history?symbols=sp500,nasdaq100,gold,btc&range=${range}`, { signal: controller.signal }).then(async (response) => { const body = await response.json() as { data?: Series[] }; if (!response.ok) throw new Error("Historical data unavailable"); setSeries(body.data ?? []); setState(body.data?.length ? "ready" : "empty"); }).catch((error: unknown) => { if ((error as Error).name !== "AbortError") setState("error"); }); return () => controller.abort(); }, [range]);
  useEffect(() => { if (state !== "ready" || !chartRef.current) return; let disposed = false; let chart: { setOption: (value: unknown) => void; resize: () => void; dispose: () => void } | undefined; let observer: ResizeObserver | undefined; (async () => { const echarts = await import("echarts"); if (disposed || !chartRef.current) return; chart = echarts.init(chartRef.current, undefined, { renderer: "canvas" }); const dates = Array.from(new Set(series.flatMap((item) => item.points.map((point) => point.date)))).sort(); chart.setOption({ animation: false, backgroundColor: "transparent", tooltip: { trigger: "axis" }, grid: { left: 44, right: 20, top: 32, bottom: 44 }, legend: { top: 0, textStyle: { color: "#9ca9b9" } }, xAxis: { type: "category", data: dates, axisLabel: { color: "#778596", hideOverlap: true } }, yAxis: { type: "value", scale: true, axisLabel: { color: "#778596" }, splitLine: { lineStyle: { color: "#243140" } } }, series: series.map((item) => ({ name: item.name, type: "line", showSymbol: false, data: dates.map((date) => item.points.find((point) => point.date === date)?.value ?? null) })) }); observer = new ResizeObserver(() => chart?.resize()); observer.observe(chartRef.current); })(); return () => { disposed = true; observer?.disconnect(); chart?.dispose(); }; }, [series, state]);
  return <section className="terminal-panel comparison-panel"><div className="terminal-panel-head"><div><span>NORMALIZED PERFORMANCE</span><h2>跨资产对比 <small>起点 = 100</small></h2></div><div className="range-tabs">{ranges.map((item) => <button className={range === item ? "active" : ""} key={item} onClick={() => { setState("loading"); setRange(item); }}>{item}</button>)}</div></div>{state === "loading" && <div className="chart-state"><i />正在请求真实历史数据…</div>}{state === "error" && <div className="chart-state error">历史数据请求失败，请稍后重试。</div>}{state === "empty" && <div className="chart-state">Data unavailable — 请配置 Market Data 与 FRED 服务端密钥。</div>}<div ref={chartRef} className={`comparison-chart ${state === "ready" ? "visible" : ""}`} /><p className="source-line">数据源：{series.map((item) => `${item.name} — ${item.source}`).join(" · ") || "待配置"}。全部在服务端标准化，浏览器不接触 API Key。</p></section>;
}
